// This file is generated by server/generate_schema.py, DO NOT MODIFY MANUALLY!

export const sourceLinks = {
    donki_flares: [
        'donki_flr_id',
        'id'
    ],
    donki_cmes: [
        'donki_cme_id',
        'id'
    ],
    lasco_cmes: [
        'lasco_cme_time',
        'time'
    ],
    cactus_cmes: [
        'cactus_cme_time',
        'time'
    ],
    r_c_icmes: [
        'rc_icme_time',
        'time'
    ],
    solarsoft_flares: [
        'solarsoft_flr_start',
        'start_time'
    ],
    legacy_noaa_flares: [
        'noaa_flr_start',
        'start_time'
    ],
    solen_holes: [
        'tag',
        'tag'
    ]
} as const;

export const sourceLabels = {
    donki_flares: 'DKI',
    donki_cmes: 'DKI',
    lasco_cmes: 'LSC',
    cactus_cmes: 'CCT',
    r_c_icmes: 'R&C',
    solarsoft_flares: 'SFT',
    legacy_noaa_flares: 'NOA'
} as const;

export const sourceColumnOrderingOptions = [
    'time',
    'position',
    'cme_speed',
    'time_desc',
    'position_desc',
    'cme_speed_desc'
] as const;

export const tablesColumns = {
    donki_flares: [
        'id',
        'event_id',
        'start_time',
        'peak_time',
        'end_time',
        'class',
        'lat',
        'lon',
        'active_region',
        'note',
        'linked_events'
    ],
    donki_cmes: [
        'id',
        'event_id',
        'time',
        'time_21_5',
        'lat',
        'lon',
        'half_width',
        'speed',
        'type',
        'data_level',
        'note',
        'linked_events',
        'enlil_id',
        'enlil_est_shock',
        'enlil_filename'
    ],
    lasco_cmes: [
        'time',
        'central_angle',
        'angular_width',
        'speed',
        'speed_2',
        'speed_2_20rs',
        'acceleration',
        'mass',
        'kinetic_energy',
        'measurement_angle',
        'note',
        'space_speed',
        'lat',
        'lon',
        'flare_class',
        'flare_onset'
    ],
    cactus_cmes: [
        'time',
        'cactus_id',
        'dt0',
        'central_angle',
        'angular_width',
        'speed',
        'dv',
        'minv',
        'maxv'
    ],
    r_c_icmes: [
        'time',
        'body_start',
        'body_end',
        'quality',
        'mc_index',
        'cmes_time'
    ],
    solardemon_dimmings: [
        'id',
        'flare_id',
        'start_time',
        'peak_time',
        'end_time',
        'intensity',
        'max_drop',
        'lat',
        'lon',
        'dist',
        'active_region',
        'image_count'
    ],
    solardemon_flares: [
        'id',
        'dimming_id',
        'start_time',
        'peak_time',
        'end_time',
        'est_class',
        'lat',
        'lon',
        'dist',
        'active_region',
        'est_flux',
        'goes_flux',
        'goes_peak_time',
        'detection_number'
    ],
    solarsoft_flares: [
        'start_time',
        'peak_time',
        'end_time',
        'class',
        'lat',
        'lon',
        'active_region'
    ],
    solen_holes: [
        'tag',
        'time',
        'polarity',
        'location',
        'comment',
        'disturbance_time'
    ],
    legacy_noaa_flares: [
        'start_time',
        'peak_time',
        'end_time',
        'class',
        'lat',
        'lon',
        'active_region',
        'psi',
        'gle',
        'dt_p10',
        'p10',
        'p60',
        'p100',
        'note'
    ],
    feid: [
        'id',
        'time',
        'duration',
        'onset_type',
        's_type',
        's_description',
        's_confidence',
        'old_magnitude',
        'gamma',
        'base_period',
        'pre_increase',
        'pre_inc_width',
        'pre_inc_direction',
        'pre_inc_duration',
        'pre_inc_magnitude',
        'pre_decrease',
        'pre_dec_width',
        'pre_dec_direction',
        'pre_dec_duration',
        'pre_dec_magnitude',
        'comment',
        'mc_time',
        'mc_duration',
        'mc_originator',
        'mc_size',
        'cme_time',
        'cme_legacy_v0',
        'flr_time'
    ],
    feid_sources: [
        'id',
        'feid_id',
        'ch_id',
        'erupt_id',
        'cr_influence'
    ],
    sources_ch: [
        'id',
        'tag',
        'chimera_time',
        'chimera_id',
        'time',
        'lat',
        'area',
        'b',
        'phi',
        'width'
    ],
    sources_erupt: [
        'id',
        'flr_start',
        'flr_peak',
        'flr_end',
        'flr_flux',
        'active_region',
        'flr_source',
        'lat',
        'lon',
        'coords_source',
        'cme_time',
        'cme_speed',
        'cme_source',
        'note',
        'solarsoft_flr_start',
        'noaa_flr_start',
        'donki_flr_id',
        'donki_cme_id',
        'lasco_cme_time',
        'cactus_cme_time',
        'rc_icme_time'
    ]
} as const;

export const filterOperations = [
    '>=',
    '<=',
    '==',
    '<>',
    'is null',
    'not null',
    'regexp'
] as const;

export const omniGroups = [
    'SW',
    'IMF',
    'MAG',
    'SWTY'
] as const;

export const omniSources = [
    'OMNIWEB',
    'GEOMAG',
    'ACE',
    'DISCOVR',
    'SWTY'
] as const;

export const omniSourceOptions = {
    'SW': [
        'OMNIWEB',
        'ACE',
        'DISCOVR'
    ],
    'IMF': [
        'OMNIWEB',
        'ACE',
        'DISCOVR'
    ],
    'MAG': [
        'OMNIWEB',
        'GEOMAG'
    ],
    'SWTY': [
        'SWTY'
    ]
} as const;

export const omniVariables = [
    {
        name: 'sc_id_imf',
        group: 'IMF'
    },
    {
        name: 'sc_id_sw',
        group: 'SW'
    },
    {
        name: 'B',
        group: 'IMF'
    },
    {
        name: 'Bm',
        group: 'IMF'
    },
    {
        name: 'Bx',
        group: 'IMF'
    },
    {
        name: 'By',
        group: 'IMF'
    },
    {
        name: 'Bz',
        group: 'IMF'
    },
    {
        name: 'By_gsm',
        group: 'IMF'
    },
    {
        name: 'Bz_gsm',
        group: 'IMF'
    },
    {
        name: 'V',
        group: 'SW'
    },
    {
        name: 'T',
        group: 'SW'
    },
    {
        name: 'D',
        group: 'SW'
    },
    {
        name: 'P',
        group: 'SW'
    },
    {
        name: 'NaNp',
        group: 'SW'
    },
    {
        name: 'Ef',
        group: 'SW'
    },
    {
        name: 'Ma',
        group: 'SW'
    },
    {
        name: 'beta',
        group: 'SW'
    },
    {
        name: 'Dst',
        group: 'MAG'
    },
    {
        name: 'AE',
        group: 'MAG'
    },
    {
        name: 'Kp',
        group: 'MAG'
    },
    {
        name: 'Ap',
        group: 'MAG'
    },
    {
        name: 'PC',
        group: 'MAG'
    },
    {
        name: 'AL',
        group: 'MAG'
    },
    {
        name: 'AU',
        group: 'MAG'
    },
    {
        name: 'SWTY',
        group: 'SWTY'
    },
    {
        name: 'KT',
        group: null
    }
] as const;

export type Column = StaticColumn | ComputedColumn;

export type StaticColumn = {
    entity: string;
    sql_name: string;
    name: string;
    description: string | null;
    dtype: 'real' | 'integer' | 'time' | 'text' | 'enum';
    is_computed: boolean;
    sql_def: string;
    not_null: boolean;
    enum: string[] | null;
    parse_name: string | null;
    parse_value: {[key: string]: string | null} | null;
    parse_stub: string | null;
    type: 'static';
};

export type CovergaeResponse = {
    start: number;
    end: number | null;
    at: number;
};

export type ComputationResponse = {
    time: number;
    done: boolean;
    error: string | null;
};

export type ComputedColumn = {
    entity: string;
    sql_name: string;
    name: string;
    description: string | null;
    dtype: 'real' | 'integer' | 'time' | 'text' | 'enum';
    is_computed: boolean;
    id: number;
    created_at: string;
    computed_at: string | null;
    owner_id: number;
    is_public: boolean;
    is_own: boolean;
    definition: string;
    type: 'computed';
};

export type Series = {
    source: 'omni' | 'gsm' | 'sat';
    name: string;
    display_name: string;
    description: string;
    dtype: 'real' | 'str';
};

export type ArgDef = {
    name: string;
    types: string[];
    dtypes: string[];
    default: string | null;
};

export type Function = {
    name: string;
    desc: string;
    args: ArgDef[];
};

export type ChangelogEntry = {
    time: number;
    author: string;
    old: string;
    new: string;
    special: 'import' | null;
};

export type ChangelogResponse = {
    fields: string[];
    events: {[key: string]: {[key: string]: (number | null | string)[][]}};
};

export type FeidInfoResponse = {
    series: Series[];
    functions: {[key: string]: Function};
    helpers: {[key: string]: [string, string]};
};

export type TableDataResponse = {
    columns: Column[];
    data: (number | string | null)[][];
    changelog: ChangelogResponse | null;
};

export type TextTransform = {
    id: number;
    search: string;
    replace: string;
    enabled: boolean;
};

export type TextTransformsSet = {
    id: number;
    author: string;
    created: string;
    modified: string;
    name: string;
    public: boolean;
    transforms: TextTransform[];
};

export type TextTransformsSetsList = {
    list: TextTransformsSet[];
};

export type Filter = {
    operation: '>=' | '<=' | '==' | '<>' | 'is null' | 'not null' | 'regexp';
    column: string;
    value: string;
};

export type Sample = {
    id: number;
    name: string;
    authors: string[];
    public: boolean;
    includes: number[];
    filters: Filter[];
    whitelist: number[];
    blacklist: number[];
    created_at: string;
    modified_at: string;
};

export interface Tables {
	donki_flares: {
		id: number;
		event_id: string | null;
		start_time: Date;
		peak_time: Date | null;
		end_time: Date | null;
		class: string | null;
		lat: number | null;
		lon: number | null;
		active_region: number | null;
		note: string | null;
		linked_events: string | null;
	},

	donki_cmes: {
		id: number;
		event_id: string | null;
		time: Date;
		time_21_5: Date | null;
		lat: number | null;
		lon: number | null;
		half_width: number | null;
		speed: number | null;
		type: string | null;
		data_level: number | null;
		note: string | null;
		linked_events: string | null;
		enlil_id: number | null;
		enlil_est_shock: Date | null;
		enlil_filename: string | null;
	},

	lasco_cmes: {
		time: Date;
		central_angle: number | null;
		angular_width: number | null;
		speed: number | null;
		speed_2: number | null;
		speed_2_20rs: number | null;
		acceleration: number | null;
		mass: number | null;
		kinetic_energy: number | null;
		measurement_angle: number | null;
		note: string | null;
		space_speed: number | null;
		lat: number | null;
		lon: number | null;
		flare_class: string | null;
		flare_onset: string | null;
	},

	cactus_cmes: {
		time: Date;
		cactus_id: number;
		dt0: number | null;
		central_angle: number | null;
		angular_width: number | null;
		speed: number | null;
		dv: number | null;
		minv: number | null;
		maxv: number | null;
	},

	r_c_icmes: {
		time: Date;
		body_start: Date;
		body_end: Date;
		quality: number;
		mc_index: number;
		cmes_time: string;
	},

	solardemon_dimmings: {
		id: number;
		flare_id: number | null;
		start_time: Date;
		peak_time: Date;
		end_time: Date;
		intensity: number | null;
		max_drop: number | null;
		lat: number | null;
		lon: number | null;
		dist: number | null;
		active_region: number | null;
		image_count: number | null;
	},

	solardemon_flares: {
		id: number;
		dimming_id: number | null;
		start_time: Date;
		peak_time: Date;
		end_time: Date;
		est_class: string | null;
		lat: number | null;
		lon: number | null;
		dist: number | null;
		active_region: number | null;
		est_flux: number | null;
		goes_flux: number | null;
		goes_peak_time: Date | null;
		detection_number: number | null;
	},

	solarsoft_flares: {
		start_time: Date;
		peak_time: Date;
		end_time: Date;
		class: string | null;
		lat: number | null;
		lon: number | null;
		active_region: number | null;
	},

	solen_holes: {
		tag: string;
		time: Date;
		polarity: string;
		location: string;
		comment: string;
		disturbance_time: Date | null;
	},

	legacy_noaa_flares: {
		start_time: Date;
		peak_time: Date;
		end_time: Date;
		class: string | null;
		lat: number | null;
		lon: number | null;
		active_region: number | null;
		psi: number | null;
		gle: number | null;
		dt_p10: number | null;
		p10: number | null;
		p60: number | null;
		p100: number | null;
		note: string | null;
	},

	feid: {
		id: number;
		time: Date;
		duration: number;
		onset_type: 'SSC' | 'iSW' | 'SI' | null;
		s_type: number | null;
		s_description: string | null;
		s_confidence: 'low' | 'avg' | 'high' | null;
		old_magnitude: number | null;
		gamma: number | null;
		base_period: Date | null;
		pre_increase: number | null;
		pre_inc_width: number | null;
		pre_inc_direction: number | null;
		pre_inc_duration: number | null;
		pre_inc_magnitude: number | null;
		pre_decrease: number | null;
		pre_dec_width: number | null;
		pre_dec_direction: number | null;
		pre_dec_duration: number | null;
		pre_dec_magnitude: number | null;
		comment: string | null;
		mc_time: Date | null;
		mc_duration: number | null;
		mc_originator: number | null;
		mc_size: number | null;
		cme_time: Date | null;
		cme_legacy_v0: number | null;
		flr_time: Date | null;
	},

	feid_sources: {
		id: number;
		feid_id: number;
		ch_id: number | null;
		erupt_id: number | null;
		cr_influence: 'primary' | 'secondary' | 'residual' | null;
	},

	sources_ch: {
		id: number;
		tag: string | null;
		chimera_time: Date | null;
		chimera_id: number | null;
		time: Date | null;
		lat: number | null;
		area: number | null;
		b: number | null;
		phi: number | null;
		width: number | null;
	},

	sources_erupt: {
		id: number;
		flr_start: Date | null;
		flr_peak: Date | null;
		flr_end: Date | null;
		flr_flux: number | null;
		active_region: number | null;
		flr_source: 'SFT' | 'DKI' | 'NOA' | 'MNL' | null;
		lat: number | null;
		lon: number | null;
		coords_source: 'FLR' | 'LSC' | 'DKI' | 'MNL' | null;
		cme_time: Date | null;
		cme_speed: number | null;
		cme_source: 'LSC' | 'DKI' | 'CCT' | 'MNL' | null;
		note: string | null;
		solarsoft_flr_start: Date | null;
		noaa_flr_start: Date | null;
		donki_flr_id: number | null;
		donki_cme_id: number | null;
		lasco_cme_time: Date | null;
		cactus_cme_time: Date | null;
		rc_icme_time: Date | null;
	},

	chimera_holes: {
		id: number | null;
		xcen: number | null;
		ycen: number | null;
		lat: number | null;
		lon: number | null;
		width_text: string | null;
		width: number | null;
		area: number | null;
		area_percent: number | null;
		b: number | null;
		b_plus: number | null;
		b_minus: number | null;
		b_max: number | null;
		b_min: number | null;
		tot_b_plus: number | null;
		tot_b_minus: number | null;
		phi: number | null;
		phi_plus: number | null;
		phi_minus: number | null;
	},

}
