
fn_call: NAME "(" (sum ("," sum)*)? ")"

?sum: product
	| sum "+" product   -> add
	| sum "-" product   -> sub

?product: atom
	| product "*" atom  -> mul
	| product "/" atom  -> div

?atom: SIGNED_NUMBER    -> number
	| ESCAPED_STRING    -> string
	| "$" NAME          -> series
	| "@" NAME          -> helper
	| "(" sum ")"
	| fn_call          

?start: sum

%import common.CNAME -> NAME
%import common.SIGNED_NUMBER
%import common.ESCAPED_STRING

%import common.WS
%ignore WS